namespace WCMS.SysCore.Resx
{
    public static class ModelDisplayName
    {
        // 公告
        public const string AnnouncementId="AnnouncementId";
        public const string Announcement_Title="Announcement_Title";
        public const string Announcement_SubTitle="Announcement_SubTitle";
        public const string Announcement_Content="Announcement_Content";
        public const string Announcement_Url="Announcement_Url";
        public const string Announcement_Categories="Announcement_Categories";
        public const string Announcement_Tags="Announcement_Tags";
        public const string Announcement_ContentStatus="Announcement_ContentStatus";
        public const string Announcement_CoverPictureId="Announcement_PictureId";
        public const string Announcement_PicDescription="Announcement_PicDescription";
        public const string Announcement_ViewCount="Announcement_ViewCount";
        public const string Announcement_StartDate="Announcement_StartDate"; //Validate_Start
        public const string Announcement_EndDate="Announcement_EndtDate"; //Validate_End
        public const string Announcement_CreationDate="Announcement_CreationDate"; //新增建立時間
        public const string Announcement_FileId="Announcement_FileId";
        public const string Announcement_ParentRowId="Announcement_ParentRowId";
        public const string Announcement_RowId="Announcement_RowId";
        public const string Announcement_Lang="Announcement_Lang";
        //廣告輪播
        public const string BannerId="BannerId";
        public const string Banner_Categories="Banner_Categories";
        public const string Banner_Interval="Banner_Interval";
        public const string Banner_Speed="Banner_Speed";
        public const string Banner_Height="Banner_Height";
        public const string Banner_Width="Banner_Width";
        public const string Banner_Effect="Banner_Effect";
        public const string Banner_PicSrcId="Banner_PicSrcId";
        public const string Banner_FontColor="Banner_FontColor";
        public const string Banner_StartDate="Banner_StartDate"; //原名Validate_Start
        public const string Banner_EndDate="Banner_EndDate"; //原名Validate_End
        public const string Banner_CreationDate="Banner_CreationDate"; //新增建立時間
        public const string Banner_Sort="Banner_Sort";
        public const string Banner_ParentRowId="Banner_ParentRowId";
        public const string Banner_RowId="Banner_RowId";
        public const string Banner_Lang="Banner_Lang";
        public const string Banner_Title="Banner_Title";
        public const string Banner_Content="Banner_Content";
        public const string Banner_Url="Banner_Url";
        public const string Banner_UrlOpen="Banner_UrlOpen";
        //類別
        public const string CategoryId="CategoryId";
        public const string Category_Module="Category_Module";
        public const string Category_Detail="Category_Breakdown"; //原名CategoryDetail
        public const string Category_RowId="Category_RowId";
        public const string Category_Lang="Category_Lang";
        public const string Category_Title="Category_Title"; //原名CategoryName
        public const string Category_CustomMade="Category_CustomMade";
        //檔案室
        public const string FileArchiveId="FileArchiveId";
        public const string FileArchive_ContentStatus="FileArchive_ContentStatus";
        public const string FileArchive_Categories="FileArchive_Categories";
        public const string FileArchive_Tags="FileArchive_Tags";
        public const string FileArchive_Lang="FileArchive_Lang";
        public const string FileArchive_Title="FileArchive_Title";
        public const string FileArchive_CustomMade="FileArchive_CustomMade";
        public const string FileArchive_ParentRowId="FileArchive_ParentRowId";
        public const string FileArchive_RowId="FileArchive_RowId";
        public const string FileArchive_FileSrcId="FileArchive_FileSrcId";
        public const string FileArchive_FileName="FileArchive_FileName";
        public const string FileArchive_StartDate="FileArchive_StartDate"; 
        public const string FileArchive_EndDate="FileArchive_EndDate";
        public const string FileArchive_CreationDate="FileArchive_CreationDate";
        public const string FileArchive_Sort="FileArchive_Sort";
        public const string FileArchive_DownloadCount="FileArchive_DownloadCount";
        //相簿
        public const string GalleryId_="GalleryId";
        public const string Gallery_Categories="Gallery_Categories";
        public const string Gallery_Tags="Gallery_Tags";
        public const string Gallery_ContentStatus="Gallery_ContentStatus";
        public const string Gallery_CoverPicSrcId="Gallery_CoverPicSrcId";
        public const string Gallery_Sort="Gallery_Sort";
        public const string Gallery_GalleryInfo="Gallery_GalleryInfo";
        public const string Gallery_Photos="Gallery_Photos"; //原名GalleryPhotos
        public const string Gallery_PhotosInfo="Gallery_PhotosInfo";
        public const string Gallery_ParentRowId="Gallery_ParentRowId";
        public const string Gallery_RowId="Gallery_RowId";
        public const string Gallery_Lang="Gallery_Lang";
        public const string Gallery_Title="Gallery_Title";
        public const string Gallery_Content="Gallery_Content";
        public const string Gallery_PicSrcId="Gallery_PicSrcId";
        //頁面
        public const string PageId="PageId";
        public const string Page_Categories="Page_Categories";
        public const string Page_ViewCount="Page_ViewCount";
        public const string Page_CustomMade="Page_CustomMade";
        public const string Page_RowId="Page_RowId";
        public const string Page_Lang="Page_Lang";
        public const string Page_Title="Page_Title";
        public const string Page_Content="Page_Content";
        //標籤
        public const string TagId="TagId";
        public const string Tag_Data="Tag_Data";
        public const string Tag_Detail="Tag_Detail";
        public const string Tag_Module="Tag_Module";
        public const string Tag_RowId="Tag_RowId";
        public const string Tag_Lang="Tag_Lang";    
        public const string Tag_TagName="Tag_TagName";
        public const string Tag_CustomMade="Tag_CustomMade";
        //網路資源
        public const string WebResourceId_="WebResourceId";
        public const string WebResource_WebResourceInfo="WebResource_WebResourceInfo";
        public const string WebResource_Categories="WebResource_Categories";
        public const string WebResource_Tags="WebResource_Tags";
        public const string WebResource_ContentStatus="WebResource_ContentStatus";             
        public const string WebResource_PicId="WebResource_PicId";
        public const string WebResource_PicDescription="WebResource_PicDescription";
        public const string WebResource_RowId="WebResource_RowId";
        public const string WebResource_Lang="WebResource_Lang";
        public const string WebResource_Title="WebResource_Title";             
        public const string WebResource_Content="WebResource_Content";
        public const string WebResource_Url="WebResource_Url"; //原名ResUrl
        public const string WebResource_UrlOpen="WebResource_UrlOpen";
        //SpecCategory
        public const string SpecCategoryId="SpecCategoryId"; //原名CategoryId
        public const string SpecCategory_Detail="SpecCategory_Detail"; 
        public const string SpecCategory_Module="SpecCategory_Module";
        public const string SpecCategory_ShowColumn="SpecCategory_ShowColumn"; //原名ShowColumnItems
        public const string SpecCategory_RowId="SpecCategory_RowId";
        public const string SpecCategory_Lang="SpecCategory_Lang";
        public const string SpecCategory_Name="SpecCategory_Name";
        public const string SpecCategory_DetailModule="SpecCategory_DetailModule"; //原名SpecCategoryDetailModel
        //SpecResearch
        public const string SpecResearchId="SpecResearchId";
        public const string SpecResearch_Detail="SpecResearch_Detail";
        public const string SpecResearch_Categories="SpecResearch_Categories";
        public const string SpecResearch_ContentStatus="SpecResearch_ContentStatus";
        public const string SpecResearch_Tags="SpecResearch_Tags";
        public const string SpecResearch_RowId="SpecResearch_RowId";
        public const string SpecResearch_Lang="SpecResearch_Lang";
        public const string SpecResearch_Year="SpecResearch_Year";
        public const string SpecResearch_AcademicYear="SpecResearch_AcademicYear";
        public const string SpecResearch_Semester="SpecResearch_Semester";
        public const string SpecResearch_DuringExecution="SpecResearch_DuringExecution";
        public const string SpecResearch_ContractPeriod="SpecResearch_ContractPeriod";
        public const string SpecResearch_ClassTime="SpecResearch_ClassTime";
        public const string SpecResearch_ProjectLeader="SpecResearch_ProjectLeader";
        public const string SpecResearch_Name="SpecResearch_Name";
        public const string SpecResearch_FacultySchedule="SpecResearch_FacultySchedule"; //原名TeachingStaffOfOurSchool
        public const string SpecResearch_ApprovalNumber="SpecResearch_ApprovalNumber";
        public const string SpecResearch_ApprovedAmount="SpecResearch_ApprovedAmount";
        public const string SpecResearch_College="SpecResearch_College";
        public const string SpecResearch_Department="SpecResearch_Department";
        public const string SpecResearch_Degree="SpecResearch_Degree"; //原名GraduationDegree
        public const string SpecResearch_CoUnits="SpecResearch_CoUnits"; //原名CooperatingUnits
        public const string SpecResearch_CoProject="SpecResearch_CoProject"; //原名CooperationProject
        public const string SpecResearch_Courses="SpecResearch_Courses";
        public const string SpecResearch_ProjectName="SpecResearch_ProjectName";
        public const string SpecResearch_PaperTitle="SpecResearch_PaperTitle";
        public const string SpecResearch_Remark="SpecResearch_Remark";
        public const string SpecResearch_Cohost1="SpecResearch_Cohost1";
        public const string SpecResearch_Cohost2="SpecResearch_Cohost2";
        public const string SpecResearch_Commissioned="SpecResearch_Commissioned";
        public const string SpecResearch_PlanAmount="SpecResearch_PlanAmount";
        public const string SpecResearch_PlanContent="SpecResearch_PlanContent";
        public const string SpecResearch_Sort="SpecResearch_Sort";
        public const string SpecResearch_PictureId="SpecResearch_PictureId";
        public const string SpecResearch_PicDescription="SpecResearch_PicDescription";
        //SpecUSR
        public const string SpecUSRId="SpecUSRId";
        public const string SpecUSR_Detail="SpecUSR_Detail";
        public const string SpecUSR_Categories="SpecUSR_Categories";
        public const string SpecUSR_ContentStatus="SpecUSR_ContentStatus";
        public const string SpecUSR_Tags="SpecUSR_Tags";
        public const string SpecUSR_PictureId="SpecUSR_PictureId";
        public const string SpecUSR_PicDescription="SpecUSR_PicDescription";
        public const string SpecUSR_RowId="SpecUSR_RowId";
        public const string SpecUSR_Lang="SpecUSR_Lang";
        public const string SpecUSR_Year="SpecUSR_Year";
        public const string SpecUSR_AcademicYear="SpecUSR_AcademicYear";
        public const string SpecUSR_Courses="SpecUSR_Courses";
        public const string SpecUSR_PracticeField="SpecUSR_PracticeField";
        public const string SpecUSR_ProjectName="SpecUSR_ProjectName";
        public const string SpecUSR_ExternalCoUnits="SpecUSR_ExternalCoUnits"; //原名ExternalCooperationUnit
        public const string SpecUSR_Department="SpecUSR_Department";
        public const string SpecUSR_DuringExecution="SpecUSR_DuringExecution";
        public const string SpecUSR_PlanAmount="SpecUSR_PlanAmount";
        public const string SpecUSR_ExecStrategy="SpecUSR_ExecStrategy"; //原名ExecutionStrategy
        public const string SpecUSR_ContentIntro="SpecUSR_ContentIntro"; //原名ContentIntroduction
        public const string SpecUSR_ProjectConcept="SpecUSR_ProjectConcept";
        public const string SpecUSR_KeyHighlights="SpecUSR_KeyHighlights"; //原名ProjectHighlights
        public const string SpecUSR_ProjectLeader="SpecUSR_ProjectLeader";
        public const string SpecUSR_Cohost1="SpecUSR_Cohost1";
        public const string SpecUSR_Cohost2="SpecUSR_Cohost2";
        public const string SpecUSR_Commissioned="SpecUSR_Commissioned";
        public const string SpecUSR_Remark="SpecUSR_Remark";
        public const string SpecUSR_Sort="SpecUSR_Sort";
  
    }
}
