// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WCMS.SysCore;

#nullable disable

namespace WCMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250710023352_AddNewColumnToYourEntity")]
    partial class AddNewColumnToYourEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WCMS.Features.SiteEdit.Announcement.AnnouncementModel", b =>
                {
                    b.Property<string>("CustomerCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerCode");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("Announcement", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Banner.Banner", b =>
                {
                    b.Property<string>("BannerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Effect")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<short>("Height")
                        .HasColumnType("smallint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<short>("Interval")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Speed")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.Property<short>("Width")
                        .HasColumnType("smallint");

                    b.HasKey("BannerId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("Banner", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Banner.BannerDetail", b =>
                {
                    b.Property<string>("BannerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<byte>("FontColor")
                        .HasColumnType("tinyint");

                    b.Property<string>("PicSrcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<byte>("URL_Open")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.HasKey("BannerId", "RowId");

                    b.ToTable("BannerDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Banner.BannerDetailInfo", b =>
                {
                    b.Property<string>("BannerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParentRowId")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BannerId", "ParentRowId", "RowId");

                    b.ToTable("BannerDetailInfo", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Category.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Category.CategoryDetail", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId", "RowId");

                    b.ToTable("CategoryDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.FileArchive.FileArchive", b =>
                {
                    b.Property<string>("FileArchiveId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoriesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TagsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.HasKey("FileArchiveId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("FileArchive", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.FileArchive.FileArchiveDetail", b =>
                {
                    b.Property<string>("FileArchiveId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParentRowId")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSrcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileArchiveId", "ParentRowId", "RowId");

                    b.ToTable("FileArchiveDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.FileArchive.FileArchiveInfo", b =>
                {
                    b.Property<string>("FileArchiveId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileArchiveId", "RowId");

                    b.ToTable("FileArchiveInfo", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Gallery.Gallery", b =>
                {
                    b.Property<string>("GalleryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoriesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverPicSrcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TagsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.HasKey("GalleryId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("Gallery", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Gallery.GalleryInfo", b =>
                {
                    b.Property<string>("GalleryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GalleryId", "RowId");

                    b.ToTable("GalleryInfo", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Gallery.GalleryPhotos", b =>
                {
                    b.Property<string>("GalleryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCovered")
                        .HasColumnType("bit");

                    b.Property<string>("PicSrcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("GalleryId", "RowId");

                    b.ToTable("GalleryPhotos", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Gallery.GalleryPhotosInfo", b =>
                {
                    b.Property<string>("GalleryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParentRowId")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GalleryId", "ParentRowId", "RowId");

                    b.ToTable("GalleryPhotosInfo", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.PageManagement.PageManagement", b =>
                {
                    b.Property<string>("PageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("PageId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("PageManagement", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.PageManagement.PageManagementDetail", b =>
                {
                    b.Property<string>("PageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageId", "RowId");

                    b.ToTable("PageManagementDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Tag.TagData", b =>
                {
                    b.Property<string>("TagId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.HasKey("TagId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("TagData", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Tag.TagDetail", b =>
                {
                    b.Property<string>("TagId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId", "RowId");

                    b.ToTable("TagDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.WebResource.WebResource", b =>
                {
                    b.Property<string>("WebResourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoriesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("SrcData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("SrcType")
                        .HasColumnType("tinyint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TagsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url_OpenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.HasKey("WebResourceId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("WebResource", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.WebResource.WebResourceInfo", b =>
                {
                    b.Property<string>("WebResourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WebResourceId", "RowId");

                    b.ToTable("WebResourceInfo", (string)null);
                });

            modelBuilder.Entity("WCMS.SpecFeatures.T1810.SiteEdit.Research.SpecResearch", b =>
                {
                    b.Property<string>("ResearchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Effect")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<short>("Height")
                        .HasColumnType("smallint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<short>("Interval")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Speed")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.Property<short>("Width")
                        .HasColumnType("smallint");

                    b.HasKey("ResearchId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("SpecResearch", (string)null);
                });

            modelBuilder.Entity("WCMS.SpecFeatures.T1810.SiteEdit.Research.SpecResearchDetail", b =>
                {
                    b.Property<string>("ResearchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("FontColor")
                        .HasColumnType("tinyint");

                    b.Property<string>("PicSrcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<byte>("URL_Open")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.HasKey("ResearchId");

                    b.ToTable("SpecResearchDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.SpecFeatures.T1810.SiteEdit.USR.SpecUSR", b =>
                {
                    b.Property<string>("USRId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Effect")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<short>("Height")
                        .HasColumnType("smallint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<short>("Interval")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Speed")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.Property<short>("Width")
                        .HasColumnType("smallint");

                    b.HasKey("USRId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("SpecUSR", (string)null);
                });

            modelBuilder.Entity("WCMS.SpecFeatures.T1810.SiteEdit.USR.SpecUSRDetail", b =>
                {
                    b.Property<string>("USRId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("FontColor")
                        .HasColumnType("tinyint");

                    b.Property<string>("PicSrcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<byte>("URL_Open")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.HasKey("USRId");

                    b.ToTable("SpecUSRDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.SysCore.Model.DataChangeLog", b =>
                {
                    b.Property<long>("DataChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DataChangeId"));

                    b.Property<DateTime>("DataChangeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataChangeId");

                    b.ToTable("DataChangeLog");
                });

            modelBuilder.Entity("WCMS.SysCore.Model.DataChangeLogDetail", b =>
                {
                    b.Property<long>("DataChangeId")
                        .HasColumnType("bigint");

                    b.Property<long>("RowId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ChangeData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<int>("TableIndex")
                        .HasColumnType("int");

                    b.HasKey("DataChangeId", "RowId");

                    b.ToTable("DataChangeLogDetail");
                });

            modelBuilder.Entity("WCMS.SysCore.Model.OperateLogModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OperateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperateLog");
                });

            modelBuilder.Entity("WCMS.SysCore.Model.RoleModel", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("EndType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.HasKey("RoleId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("WCMS.SysCore.Model.UserModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("AccountStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("WCMS.SysCore.Model.DataChangeLogDetail", b =>
                {
                    b.HasOne("WCMS.SysCore.Model.DataChangeLog", "DataChangeLog")
                        .WithMany()
                        .HasForeignKey("DataChangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataChangeLog");
                });
#pragma warning restore 612, 618
        }
    }
}
