// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WCMS.SysCore;

#nullable disable

namespace WCMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WCMS.Features.SiteEdit.Announcement.Announcement", b =>
                {
                    b.Property<string>("AnnouncementId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Categories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ContentStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("Announcement", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Announcement.AnnouncementDetail", b =>
                {
                    b.Property<string>("AnnouncementId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnnouncementId", "RowId");

                    b.ToTable("AnnouncementDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Announcement.AnnouncementDetailFile", b =>
                {
                    b.Property<string>("AnnouncementId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParentRowId")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnnouncementId", "ParentRowId", "RowId");

                    b.ToTable("AnnouncementDetailFile", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Banner.Banner", b =>
                {
                    b.Property<string>("BannerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BannerCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<short>("Height")
                        .HasColumnType("smallint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<short>("Interval")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Speed")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.Property<short>("Width")
                        .HasColumnType("smallint");

                    b.HasKey("BannerId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("Banner", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Banner.BannerDetail", b =>
                {
                    b.Property<string>("BannerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("FontColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicSrcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("BannerId", "RowId");

                    b.ToTable("BannerDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Banner.BannerDetailInfo", b =>
                {
                    b.Property<string>("BannerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParentRowId")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("URL_Open")
                        .HasColumnType("tinyint");

                    b.HasKey("BannerId", "ParentRowId", "RowId");

                    b.ToTable("BannerDetailInfo", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Category.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("CategoryId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Category.CategoryDetail", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId", "RowId");

                    b.ToTable("CategoryDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.FileArchive.FileArchive", b =>
                {
                    b.Property<string>("FileArchiveId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoriesId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ContentStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("FileArchiveId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("FileArchive", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.FileArchive.FileArchiveDetail", b =>
                {
                    b.Property<string>("FileArchiveId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParentRowId")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSrcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileArchiveId", "ParentRowId", "RowId");

                    b.ToTable("FileArchiveDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.FileArchive.FileArchiveInfo", b =>
                {
                    b.Property<string>("FileArchiveId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileArchiveId", "RowId");

                    b.ToTable("FileArchiveInfo", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Gallery.Gallery", b =>
                {
                    b.Property<string>("GalleryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ContentStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("CoverPicSrcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("GalleryId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("Gallery", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Gallery.GalleryInfo", b =>
                {
                    b.Property<string>("GalleryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GalleryId", "RowId");

                    b.ToTable("GalleryInfo", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Gallery.GalleryPhotos", b =>
                {
                    b.Property<string>("GalleryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCovered")
                        .HasColumnType("bit");

                    b.Property<string>("PicSrcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("GalleryId", "RowId");

                    b.ToTable("GalleryPhotos", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Gallery.GalleryPhotosInfo", b =>
                {
                    b.Property<string>("GalleryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ParentRowId")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GalleryId", "ParentRowId", "RowId");

                    b.ToTable("GalleryPhotosInfo", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.PageManagement.PageManagement", b =>
                {
                    b.Property<string>("PageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("PageId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("PageManagement", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.PageManagement.PageManagementDetail", b =>
                {
                    b.Property<string>("PageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PageId", "RowId");

                    b.ToTable("PageManagementDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Tag.TagData", b =>
                {
                    b.Property<string>("TagId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("TagId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("TagData", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Tag.TagDetail", b =>
                {
                    b.Property<string>("TagId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId", "RowId");

                    b.ToTable("TagDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.WebResource.WebResource", b =>
                {
                    b.Property<string>("WebResourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ContentStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("WebResourceId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("WebResource", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.WebResource.WebResourceInfo", b =>
                {
                    b.Property<string>("WebResourceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url_OpenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WebResourceId", "RowId");

                    b.ToTable("WebResourceInfo", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SysSetting.FileManagement.FileInfoDownloadModel", b =>
                {
                    b.Property<string>("InternalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("DownloadStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DownloadTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("DownloadUserIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefererURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InternalId", "RowId");

                    b.ToTable("FileInfoDownload", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SysSetting.FileManagement.FileInfoSyncModel", b =>
                {
                    b.Property<string>("InternalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("DestFullPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestNode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExecuteTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<byte>("FileStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("SrcFullPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SrcIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SrcNode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InternalId", "RowId");

                    b.ToTable("FileInfoSync", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SysSetting.FileManagement.FileManagementModel", b =>
                {
                    b.Property<string>("InternalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileSHA256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<byte>("FileStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("ImportLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("InternalId");

                    b.HasIndex("FileSHA256");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("FileManagement", (string)null);
                });

            modelBuilder.Entity("WCMS.SpecFeatures.T1810.SiteEdit.SpecCategory.SpecCategoryDetailModel", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId", "RowId");

                    b.ToTable("SpecCategoryDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.SpecFeatures.T1810.SiteEdit.SpecCategory.SpecCategoryModel", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShowColumnItems")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("CategoryId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("SpecCategory", (string)null);
                });

            modelBuilder.Entity("WCMS.SpecFeatures.T1810.SiteEdit.SpecResearch.SpecResearchDetailModel", b =>
                {
                    b.Property<string>("ResearchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("FontColor")
                        .HasColumnType("tinyint");

                    b.Property<string>("PicSrcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<byte>("URL_Open")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("ResearchId");

                    b.ToTable("SpecResearchDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.SpecFeatures.T1810.SiteEdit.SpecResearch.SpecResearchModel", b =>
                {
                    b.Property<string>("ResearchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("ResearchId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("SpecResearch", (string)null);
                });

            modelBuilder.Entity("WCMS.SpecFeatures.T1810.SiteEdit.SpecUSR.SpecUSRDetail", b =>
                {
                    b.Property<string>("USRId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("FontColor")
                        .HasColumnType("tinyint");

                    b.Property<string>("PicSrcId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<byte>("URL_Open")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("USRId");

                    b.ToTable("SpecUSRDetail", (string)null);
                });

            modelBuilder.Entity("WCMS.SpecFeatures.T1810.SiteEdit.SpecUSR.SpecUSRModel", b =>
                {
                    b.Property<string>("USRId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Effect")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<short>("Height")
                        .HasColumnType("smallint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<short>("Interval")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Speed")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.Property<short>("Width")
                        .HasColumnType("smallint");

                    b.HasKey("USRId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("SpecUSR", (string)null);
                });

            modelBuilder.Entity("WCMS.SysCore.Model.DataChangeLog", b =>
                {
                    b.Property<long>("DataChangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DataChangeId"));

                    b.Property<DateTime>("DataChangeTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataChangeId");

                    b.ToTable("DataChangeLog");
                });

            modelBuilder.Entity("WCMS.SysCore.Model.DataChangeLogDetail", b =>
                {
                    b.Property<long>("DataChangeId")
                        .HasColumnType("bigint");

                    b.Property<long>("RowId")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("ChangeData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte>("RowState")
                        .HasColumnType("tinyint");

                    b.Property<int>("TableIndex")
                        .HasColumnType("int");

                    b.HasKey("DataChangeId", "RowId");

                    b.ToTable("DataChangeLogDetail");
                });

            modelBuilder.Entity("WCMS.SysCore.Model.OperateLogModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OperateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("PK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperateLog");
                });

            modelBuilder.Entity("WCMS.SysCore.Model.RoleModel", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<byte>("EndType")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("RoleId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("WCMS.SysCore.Model.UserModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("AccountStatus")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreateUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("DataStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("FormStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("InvalidTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("InvalidUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIniData")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgLvId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Validate_End")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("Validate_Start")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("UserId");

                    b.HasIndex("InternalId")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Announcement.AnnouncementDetail", b =>
                {
                    b.HasOne("WCMS.Features.SiteEdit.Announcement.Announcement", null)
                        .WithMany("AnnouncementDetail")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Category.CategoryDetail", b =>
                {
                    b.HasOne("WCMS.Features.SiteEdit.Category.Category", null)
                        .WithMany("CategoryDetail")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.PageManagement.PageManagementDetail", b =>
                {
                    b.HasOne("WCMS.Features.SiteEdit.PageManagement.PageManagement", null)
                        .WithMany("PageManagementDetail")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Tag.TagDetail", b =>
                {
                    b.HasOne("WCMS.Features.SiteEdit.Tag.TagData", null)
                        .WithMany("TagDetail")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WCMS.Features.SysSetting.FileManagement.FileInfoDownloadModel", b =>
                {
                    b.HasOne("WCMS.Features.SysSetting.FileManagement.FileManagementModel", null)
                        .WithMany("FileInfoDownload")
                        .HasForeignKey("InternalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WCMS.Features.SysSetting.FileManagement.FileInfoSyncModel", b =>
                {
                    b.HasOne("WCMS.Features.SysSetting.FileManagement.FileManagementModel", null)
                        .WithMany("FileInfoSync")
                        .HasForeignKey("InternalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WCMS.SysCore.Model.DataChangeLogDetail", b =>
                {
                    b.HasOne("WCMS.SysCore.Model.DataChangeLog", "DataChangeLog")
                        .WithMany()
                        .HasForeignKey("DataChangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataChangeLog");
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Announcement.Announcement", b =>
                {
                    b.Navigation("AnnouncementDetail");
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Category.Category", b =>
                {
                    b.Navigation("CategoryDetail");
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.PageManagement.PageManagement", b =>
                {
                    b.Navigation("PageManagementDetail");
                });

            modelBuilder.Entity("WCMS.Features.SiteEdit.Tag.TagData", b =>
                {
                    b.Navigation("TagDetail");
                });

            modelBuilder.Entity("WCMS.Features.SysSetting.FileManagement.FileManagementModel", b =>
                {
                    b.Navigation("FileInfoDownload");

                    b.Navigation("FileInfoSync");
                });
#pragma warning restore 612, 618
        }
    }
}
